// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.898
package template

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Home() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><script src=\"https://cdn.tailwindcss.com\"></script></head><body class=\"flex flex-col min-w-full min-h-screen justify-center items-center\"><form class=\"flex flex-col space-y-3 p-3 w-1/3 h-1/3 border-2 border-slate-600 rounded-md\" action=\"/connection\" method=\"POST\" target=\"_blank\"><section class=\"flex justify-between\"><span class=\"w-1/3\">Protocol: </span> <input class=\"w-2/3 px-2 border-2 border-slate-600 rounded-md\" type=\"text\" name=\"protocol\" value=\"rdp\"></section><section class=\"flex justify-between\"><span class=\"w-1/3\">Hostname: </span> <input class=\"w-2/3 px-2 border-2 border-slate-600 rounded-md\" type=\"text\" name=\"hostname\"></section><section class=\"flex justify-between\"><span class=\"w-1/3\">Port: </span> <input class=\"w-2/3 px-2 border-2 border-slate-600 rounded-md\" name=\"port\" value=\"3389\"></section><section class=\"flex justify-between\"><span class=\"w-1/3\">Username: </span> <input class=\"w-2/3 px-2 border-2 border-slate-600 rounded-md\" type=\"text\" name=\"username\"></section><section class=\"flex justify-between\"><span class=\"w-1/3\">Password: </span> <input class=\"w-2/3 px-2 border-2 border-slate-600 rounded-md\" type=\"password\" name=\"password\"></section><section class=\"flex justify-between\"><span class=\"w-1/3\">Security: </span> <input class=\"w-2/3 px-2 border-2 border-slate-600 rounded-md\" type=\"text\" name=\"security\" value=\"nla\"></section><section class=\"flex items-center\"><span>Ignore Certificate: </span> <input class=\"ml-3 border-2 border-slate-600 rounded-md\" type=\"checkbox\" name=\"ignoreCertificate\" checked></section><button class=\"w-1/3 p-3 border-2 border-slate-600 rounded-md place-self-center\" type=\"submit\">Connect</button></form></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func Connection() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<!doctype html><html><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><script src=\"https://cdn.tailwindcss.com\"></script></head><body id=\"display\" class=\"min-w-full min-h-screen overflow-hidden\"></body><script src=\"/static/js/guacamole.min.js\"></script><script src=\"/static/js/remote-connection.js\"></script></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
